#!/bin/bash

#generate random user
function genUser {
        user=$[ 1 + $[ RANDOM % 99999999 ]]
        
        NAMES="$(< /home/max/newMEGACount)" #names from names.txt file
        for i in $NAMES; do
                if [ "$user" -eq "$i" ]
                then
                        genUser
                fi
        done
}

#generate random password
password=`date +%s | sha256sum | base64 | head -c 20 ; echo`

#run function
genUser

#authenticate username and password from mega
sudo /home/max/createMega $password $user

#store user
echo -e "$user\n" >> /home/max/newMEGACount

echo "----->$user@createmega.xyz:$password"
